apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: FLASK_APP
          envFrom:
            - configMapRef:
                name: hello-world-env
            - secretRef:
                name: hello-world-secrets